<?php

// $Id$

/**
 * @file
 * General functions
 */
function rtmpswitcher_menu() {
  $items['rtmpswitcher'] = array(
    'title' => t('RTMP Video Switcher'),
    'page callback' => 'channel_list',
    'access arguments' => array('access content'),
//    'access arguments' => array('administer site configuration'),
  );

  $items['rtmpswitcher/list'] = array(
    'title' => t('Channels list'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );

  $items['rtmpswitcher/addchannel'] = array(
    'title' => t('Add channel'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('channel_form'),
    'access arguments' => array('access content'),
//    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  $items['rtmpswitcher/%channel/edit'] = array(
    'title' => t('Edit channel'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('channel_form', 1),
    'access callback' => TRUE,
//    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  $items['rtmpswitcher/%channel/delete'] = array(
    'title' => t('Delete channel'),
    'page callback' => 'channel_delete',
    'page arguments' => array(1),
    'access callback' => TRUE,
//    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function channel_list() {
  try {
    $tableHeader = array(t('Video'), t('Name'), t('Type'), t('Description'), t('Actions') );
    $tableData = array();
    db_set_active('video_switch');
    $res = db_query(
        "select " .
        "channels.id as id, channels.name as name, channels.is_enabled as is_enabled, channels.comment as comment, channel_types.chan_type as chan_type, channels.uri as uri, channels.embed_html as embed_html " .
        "from channels " .
        "join channel_types on channel_types.id=channels.chan_type;");

    foreach ($res as $row) {
      $data[] = $row;
    }
    db_set_active('default');

    foreach ($data as $ch) {
      $actions = array(
        l(t('edit'), 'rtmpswitcher/' . $ch->id . '/edit'),
        l(t('delete'), 'rtmpswitcher/' . $ch->id . '/delete', array('query' => array('token' => drupal_get_token('channel-' . $ch->id)))),
      );

      $tableData[] = array(
        'data' => array(
          $ch->embed_html,
          l($ch->name, $ch->uri),
          $ch->chan_type,
          $ch->comment,
          implode(' | ', $actions)
        ),
        'id' => array('ch-' . $ch->id),
      );
    }

    return theme('table', array('header' => $tableHeader, 'rows' => $tableData));
  } catch (Exception $e) {
    db_set_active('default');
  }
}

function channel_form($form, &$form_state, $ch = null) {
  db_set_active('video_switch');
  $res = db_query("select * from channel_types;");

  foreach ($res as $row) {
    $channel_types[$row->id] = $row->chan_type;
  }
  db_set_active('default');

  $form['name'] = array(
    '#title' => t('Name'),
//    '#description' => t('Channel name'),
    '#type' => 'textfield',
    '#default_value' => $ch ? $ch->name : '',
    '#required' => true,
  );

  $form['chan_type'] = array(
    '#title' => t('Type'),
//    '#description' => t('Channel type'),
    '#type' => 'select',
    '#options' => $channel_types,
    '#default_value' => $ch ? $ch->chan_type : 1,
    '#required' => true,
  );

  $form['uri'] = array(
    '#title' => t('URI'),
//    '#description' => t('Channel URI'),
    '#type' => 'textfield',
    '#default_value' => $ch ? $ch->uri : '',
    '#required' => true,
  );

  $form['comment'] = array(
    '#title' => t('Comment'),
//    '#description' => t('Channel description'),
    '#type' => 'textfield',
    '#default_value' => $ch ? $ch->comment : '',
  );

  $form['embed_html'] = array(
    '#title' => t('HTML code of embedded player'),
//    '#description' => t('Channel description'),
    '#type' => 'textarea',
    '#default_value' => $ch ? $ch->embed_html : '',
  );

  $form['disable'] = array(
    '#title' => t('Disable channel'),
//    '#description' => t('Disable channel monitoring'),
    '#type' => 'checkbox',
    '#default_value' => $ch ? !$ch->is_enabled : false,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => $ch ? t('Save') : t('Add'),
  );

  if ($ch) {
    $form['id'] = array(
      '#type' => 'value',
      '#value' => $ch->id,
    );
  }
  else {
    $form['id'] = array(
      '#type' => 'value',
      '#value' => NULL,
    );
  }

  return $form;
}

function channel_form_submit($form, &$form_state) {
  $ch = array(
    'name' => $form_state['values']['name'],
    'chan_type' => $form_state['values']['chan_type'],
    'comment' => $form_state['values']['comment'],
    'uri' => $form_state['values']['uri'],
    'embed_html' => $form_state['values']['embed_html'],
    'is_enabled' => (int) (!$form_state['values']['disable']),
  );
  $chId = $form_state['values']['id'];

  try {
    db_set_active('video_switch');
    if ($chId) {
      db_update('channels')->fields($ch)->condition('id', $chId, '=')
          ->execute();
    }
    else {
      db_insert('channels')->fields($ch)->execute();
    }
    db_set_active('default');
  } catch (Exception $e) {
    db_set_active('default');
    return NULL;
  }

  drupal_set_message(t('Channel submitted'));

  drupal_goto('rtmpswitcher');
}

function channel_delete($ch) {
//  return var_dump($ch);

  if (!drupal_valid_token($_GET['token'], 'channel-' . $ch->id)) {
    return drupal_access_denied();
  }

  try {
    db_set_active('video_switch');
    $ret = db_query("delete  FROM {channels}  where {channels}.id = :id", array(':id' => $ch->id));
    db_set_active('default');
  } catch (Exception $e) {
    db_set_active('default');
    return NULL;
  }

  drupal_set_message(t('Channel deleted'));
  drupal_goto('rtmpswitcher');
}

function channel_load($id) {
  try {
    db_set_active('video_switch');
    $ret = db_query("SELECT * FROM {channels}  where {channels}.id = :id", array(':id' => $id))->fetchObject();
    db_set_active('default');

    return $ret;
  } catch (Exception $e) {
    db_set_active('default');
    return NULL;
  }
}

